
[[_installation]]
= Installation

Micronaut NewRelic helps send custom events to NewRelic.

There are two implementations of the client, one using Micronaut HTTP client with
the NewRelic Java library, and the default implementation which logs the events' JSON
to the `com.agorapulse.micronaut.newrelic.NewRelicInsightsService` log.

== Default Implementation

If you are developing a library, you can let the developers choose the
implementation later. You only need to depend on this library:

[source,groovy,subs='verbatim,attributes']
----
repositories {
    mavenCentral()
}

dependencies {
    // standard Micronaut dependencies
    implementation 'com.agorapulse:micronaut-newrelic:{project-version}'
}
----

== HTTP Client

To enable the HTTP client implementation, add a dependency on this library
and `micronaut-http-client`:

[source,groovy,subs='verbatim,attributes']
----
repositories {
    mavenCentral()
}

dependencies {
    // standard Micronaut dependencies
    implementation 'com.agorapulse:micronaut-newrelic:{project-version}'
    implementation 'io.micronaut:micronaut-http-client'

    // for reporting Micronaut URL from controllers
    implementation 'com.agorapulse:micronaut-newrelic-http:{project-version}'
}
----

You must also specify values for the `newrelic.url` and `newrelic.token` properties:

[source,yml,subs='verbatim,attributes']
----
newrelic:
  url: https://insights-collector.newrelic.com/v1/accounts/123456
  token: abcdef1234567890
----

== NewRelic Library

To enable the NewRelic client implementation, add a dependency on this library
and the NewRelic Java library. The Java agent must be running alongside.

[source,groovy,subs='verbatim,attributes']
----
repositories {
    mavenCentral()
}

dependencies {
    // standard Micronaut dependencies
    implementation 'com.agorapulse:micronaut-newrelic:{project-version}'
    implementation 'com.newrelic.agent.java:newrelic-api:4.9.0'

    // for reporting Micronaut URL from controllers
    implementation 'com.agorapulse:micronaut-newrelic-http:{project-version}'
}
----

