
[[_usage]]
= Usage

Micronaut NewRelic library provides the `NewRelicInsightsService` bean with two methods, `createEvent` and `createEvents`:

[source,java,subs='verbatim,attributes']
----
newRelicInsightsService.createEvent(NewRelicInsightsEvent.create("TestEvent", "key", 10));
newRelicInsightsService.createEvents(Arrays.asList(
    new MyEvent().withKey("key").withValue(20),
    NewRelicInsightsEvent.create("TestEvent", "key", 10)
));
----

Events can be instances of any class annotated with `@Introspected`.
In that case the event type will be same as the name of the event class,
e.g., `MyEvent`.

WARNING: If you use the library in a non-Micronaut environment (e.g., Grails), ensure your `@Introspected` classes are processed by `micronaut-inject-java` or `micronaut-inject-groovy`.

The events can optionally implement the `NewRelicInsightsEvent` interface,
which let you fine-tune the `eventType` and `timestamp` properties.

There might be some HTTP communication issues when communicating with the NewRelic Insights API when using the HTTP client. By default, the error is only logged as a warning. You can fine tune the logging level by setting `newrelic.log-level` Micronaut property to one of the possible values: `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, `OFF`.

You can mark your events with `@Critical` annotation to try to retry the event delivery when there is any communication issue such as connection timeout or reset. The default number of retries is 3, but you can change it by setting the `newrelic.retry-count` Micronaut property. If you are using `NewRelicInsightsEvent` interface, you can also mark your event critical by returning `true` from the `isCritical` method. If you are not implementing the `NewRelicInsightsEvent` interface then you can still add `critical` property to your event and set it to `true`.
