/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2022-2026 Agorapulse.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
plugins {
    id 'com.agorapulse.gradle.aggregate-checkstyle-reports'
    id 'com.agorapulse.gradle.aggregate-codenarc-reports'
    id 'com.agorapulse.gradle.aggregate-jacoco-reports'
    id 'io.github.gradle-nexus.publish-plugin'
}

if (!project.hasProperty('ossrhUsername'))      ext.ossrhUsername       = System.getenv('SONATYPE_USERNAME') ?: '**UNDEFINED**'
if (!project.hasProperty('ossrhPassword'))      ext.ossrhPassword       = System.getenv('SONATYPE_PASSWORD') ?: '**UNDEFINED**'
if (!project.hasProperty('signingKeyId'))       ext.signingKeyId        = System.getenv('SIGNING_KEY_ID') ?: '**UNDEFINED**'
if (!project.hasProperty('signingPassword'))    ext.signingPassword     = System.getenv('SIGNING_PASSWORD') ?: '**UNDEFINED**'
if (!project.hasProperty('signingSecretKey'))   ext.signingSecretKey    = System.getenv('SIGNING_SECRET_KEY_PATH') ? rootProject.file(System.getenv('SIGNING_SECRET_KEY_PATH')).text : '**UNDEFINED**'

nexusPublishing {
    repositories {
        sonatype {
            nexusUrl = uri('https://s01.oss.sonatype.org/service/local/')
            snapshotRepositoryUrl = uri('https://s01.oss.sonatype.org/content/repositories/snapshots/')
            username = ossrhUsername
            password = ossrhPassword
        }
    }
}

allprojects {
    repositories {
        mavenCentral()
        maven { url = 'https://repo.spring.io/release' }
    }
}

def micronautModules = subprojects.findAll {
    it.projectDir.parentFile.name in ['libs', 'test-projects']
}

configure(micronautModules) { Project sub ->
    sub.afterEvaluate {
        sub.java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(25)
            }
        }

        sub.micronaut {
            importMicronautPlatform = true
            testRuntime 'spock'
            processing {
                incremental false
            }
        }
    }

    sub.tasks.withType(Test).configureEach {
        useJUnitPlatform()
        systemProperty 'user.timezone', 'UTC'
        systemProperty 'user.language', 'en'
    }

    sub.tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.compilerArgs.add('-parameters')
    }

    sub.tasks.withType(Javadoc).configureEach {
        options.encoding = 'UTF-8'
        options.addStringOption('Xdoclint:none', '-quiet')
    }

    sub.dependencies {
        testCompileOnly 'io.micronaut:micronaut-inject-groovy'
        testImplementation 'io.github.cjstehno.ersatz:ersatz:4.0.0'
        testImplementation 'io.github.cjstehno.ersatz:ersatz-groovy:4.0.0'
    }
}

def libModules = subprojects.findAll { it.projectDir.parentFile.name == 'libs' }

configure(libModules) { Project sub ->
    sub.plugins.apply('maven-publish')
    sub.plugins.apply('signing')

    sub.java {
        withJavadocJar()
        withSourcesJar()
    }

    sub.publishing {
        publications {
            maven(MavenPublication) {
                from sub.components.java
                pom {
                    name = sub.name
                    description = 'Micronaut Newrelic Library'
                    url = "https://github.com/${slug}"
                    licenses {
                        license {
                            name = 'The Apache License, Version 2.0'
                            url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                        }
                    }
                    developers {
                        developer {
                            id = 'musketyr'
                            name = 'Vladimir Orany'
                        }
                    }
                    scm {
                        connection = "scm:git:git@github.com:${slug}.git"
                        developerConnection = "scm:git:git@github.com:${slug}.git"
                        url = "https://github.com/${slug}"
                    }
                }
            }
        }
        repositories {
            maven {
                name = 'localRelease'
                url = "${rootProject.layout.buildDirectory.get().asFile}/repos/local/release"
            }
            maven {
                name = 'localSnapshot'
                url = "${rootProject.layout.buildDirectory.get().asFile}/repos/local/snapshot"
            }
        }
    }

    boolean releasing = (rootProject.findProperty('release') ?: false).toBoolean()
    if (releasing) {
        sub.signing {
            useInMemoryPgpKeys(signingKeyId, signingSecretKey, signingPassword)
            sign sub.publishing.publications.maven
        }
    }
}
