/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2022-2026 Agorapulse.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = uri('https://agorapulse.jfrog.io/agorapulse/gradle-plugins-releases-local/') }
        mavenCentral()
    }
    plugins {
        id 'com.agorapulse.gradle.settings'                     version agorapulseGradlePluginsVersion
        id 'com.agorapulse.gradle.gradle-enterprise'            version agorapulseGradlePluginsVersion
        id 'com.agorapulse.gradle.remote-cache'                 version agorapulseGradlePluginsVersion
        id 'com.agorapulse.gradle.internal-version-catalog'     version agorapulseGradlePluginsVersion
        id 'com.agorapulse.gradle.groovy-common-configuration'  version agorapulseGradlePluginsVersion
        id 'com.agorapulse.gradle.micronaut-library'            version agorapulseGradlePluginsVersion
        id 'com.agorapulse.gradle.micronaut-compatibility'      version agorapulseGradlePluginsVersion
        id 'com.agorapulse.gradle.error-prone'                  version agorapulseGradlePluginsVersion
        id 'com.agorapulse.gradle.aggregate-checkstyle-reports' version agorapulseAggregateChecksVersion
        id 'com.agorapulse.gradle.aggregate-codenarc-reports'   version agorapulseAggregateChecksVersion
        id 'com.agorapulse.gradle.aggregate-jacoco-reports'     version agorapulseGradlePluginsVersion
        id 'com.agorapulse.gradle.guide'                        version agorapulseGradlePluginsVersion
        id 'org.ajoberstar.git-publish'                         version gitPublishPluginVersion
        id 'io.github.gradle-nexus.publish-plugin'              version nexusPluginVersion
    }
}

buildscript {
    repositories {
        gradlePluginPortal()
        maven { url = uri('https://agorapulse.jfrog.io/agorapulse/gradle-plugins-releases-local/') }
        mavenCentral()
    }
    dependencies {
        classpath "io.micronaut.gradle:micronaut-minimal-plugin:${micronautGradlePluginVersion}"
        classpath "com.agorapulse.gradle:micronaut-library:${agorapulseGradlePluginsVersion}"
        classpath "com.agorapulse.gradle:micronaut-compatibility:${agorapulseGradlePluginsVersion}"
        classpath "com.agorapulse.gradle:groovy-common-configuration:${agorapulseGradlePluginsVersion}"
        classpath "com.agorapulse.gradle:error-prone:${agorapulseGradlePluginsVersion}"
    }
}

plugins {
    id 'com.agorapulse.gradle.settings'
    id 'com.agorapulse.gradle.gradle-enterprise'
    id 'com.agorapulse.gradle.remote-cache'
    id 'com.agorapulse.gradle.internal-version-catalog'
}

gradleProjects {
    directories = ['libs', 'docs', 'test-projects']

    plugins {
        dirs(['libs', 'test-projects']) {
            id 'groovy'
            id 'com.agorapulse.gradle.micronaut-library'
            id 'com.agorapulse.gradle.groovy-common-configuration'
            id 'com.agorapulse.gradle.micronaut-compatibility'
            id 'com.agorapulse.gradle.error-prone'
        }
    }
}

rootProject.name = 'micronaut-newrelic-root'
