name: Check

on: [ push, pull_request ]
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - uses: gradle/gradle-command-action@v2
        with:
          arguments: check coveralls
